# Generated by Django 5.1.5 on 2025-02-17 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_usersubmission'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hgallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='SEO')),
            ],
        ),
    ]
