# Generated by Django 5.2 on 2025-05-14 03:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_hgallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=300)),
                ('review', models.TextField(max_length=2000)),
                ('rating', models.PositiveIntegerField(default=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dentist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='account.dentist')),
            ],
        ),
    ]
