# Generated by Django 5.1.5 on 2025-05-14 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_patientreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='dentist',
            name='clinic_name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
