# Generated by Django 5.2 on 2025-05-30 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_dentist_clinic_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
