# Generated by Django 3.2.25 on 2025-08-04 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_city_latitude_city_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blog_banner_lg_alt',
            field=models.CharField(blank=True, max_length=156, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='blog_banner_sm_alt',
            field=models.CharField(blank=True, max_length=156, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='image_alt',
            field=models.CharField(blank=True, max_length=156, null=True),
        ),
    ]
