# Generated by Django 5.2 on 2025-07-21 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_alter_dentist_lat_alter_dentist_long'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dentist',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dentist',
            name='long',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
