# Generated by Django 5.2 on 2025-08-02 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_alter_dentist_lat_alter_dentist_long'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blog_banner_lg_alt',
            field=models.CharField(blank=True, max_length=156, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='blog_banner_sm_alt',
            field=models.CharField(blank=True, max_length=156, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='image_alt',
            field=models.CharField(blank=True, max_length=156, null=True),
        ),
    ]
