# Generated by Django 3.2.25 on 2025-08-08 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_auto_20250804_0311'),
        ('account', '0020_blog_blog_banner_lg_alt_blog_blog_banner_sm_alt_and_more'),
    ]

    operations = [
    ]
