# Generated by Django 5.2 on 2025-08-22 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_blog_blog_banner_lg_alt_blog_blog_banner_sm_alt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='city',
            field=models.CharField(blank=True, max_length=156, null=True),
        ),
    ]
