# Generated by Django 3.2.25 on 2025-08-08 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0021_merge_20250808_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='dentist',
            name='alt_text',
            field=models.CharField(blank=True, help_text='Alternative text for the image', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='gallery',
            name='alt_text',
            field=models.CharField(blank=True, help_text='Alternative text for the image', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hgallery',
            name='alt_text',
            field=models.CharField(blank=True, help_text='Alternative text for the image', max_length=255, null=True),
        ),
    ]
