# Generated by Django 5.2 on 2025-08-22 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0021_contact_city_dentist_alt_text_gallery_alt_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubmission',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usersubmission',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
