# Generated by Django 5.2 on 2025-08-22 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0022_dentist_alt_text_gallery_alt_text_hgallery_alt_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubmission',
            name='doctor_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
