# Generated by Django 5.2 on 2025-08-26 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0023_dentist_alt_text_gallery_alt_text_hgallery_alt_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dentist',
            name='alt_text',
            field=models.CharField(blank=True, help_text='Alternative text for the image', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='gallery',
            name='alt_text',
            field=models.CharField(blank=True, help_text='Alternative text for the image', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hgallery',
            name='alt_text',
            field=models.CharField(blank=True, help_text='Alternative text for the image', max_length=255, null=True),
        ),
    ]
