# Generated by Django 3.2.25 on 2025-08-22 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0022_auto_20250808_1243'),
        ('account', '0023_dentist_alt_text_gallery_alt_text_hgallery_alt_text_and_more'),
    ]

    operations = [
    ]
