# Generated by Django 5.2 on 2025-08-27 02:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0024_dentist_alt_text_gallery_alt_text_hgallery_alt_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='DentistRedirect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_slug', models.SlugField(unique=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.city')),
            ],
        ),
    ]
