# Generated by Django 3.2.25 on 2025-08-27 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0024_merge_20250822_1323'),
        ('account', '0025_dentistredirect'),
    ]

    operations = [
    ]
