# Generated by Django 5.2 on 2025-09-18 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0026_dentistconnect'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='schema',
            field=models.TextField(blank=True, null=True),
        ),
    ]
