# Generated by Django 3.2.25 on 2025-09-25 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0026_merge_0024_merge_20250822_1323_0025_dentistredirect'),
        ('account', '0027_blog_schema'),
    ]

    operations = [
    ]
