# Generated by Django 3.2.25 on 2025-10-18 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0028_merge_20250925_1121'),
    ]

    operations = [
        migrations.CreateModel(
            name='DentistConnectNew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=1256, null=True)),
                ('email', models.CharField(blank=True, max_length=180, null=True)),
                ('phone', models.CharField(max_length=156)),
                ('clinic_name', models.CharField(blank=True, max_length=2084, null=True)),
                ('city', models.CharField(blank=True, max_length=1084, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
