# Generated by Django 5.2 on 2025-11-13 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0029_dentistconnectnew'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='blog_banner_lg',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='blog_banner_lg_alt',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='blog_banner_sm',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='blog_banner_sm_alt',
        ),
    ]
