# Generated by Django 5.2 on 2025-11-27 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0032_beforeafter'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubmission',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
