# Generated by Django 5.2 on 2025-12-19 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0033_usersubmission_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='dentist',
            name='dentist_image',
            field=models.ImageField(blank=True, null=True, upload_to='Image'),
        ),
        migrations.AlterField(
            model_name='dentist',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to='DentistImage'),
        ),
    ]
