# Generated by Django 5.2 on 2025-12-22 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0034_auto_20251219_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientreview',
            name='reviewlink',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
    ]
