# Generated by Django 5.2 on 2026-01-21 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0037_smiledesignlead'),
    ]

    operations = [
        migrations.CreateModel(
            name='Awards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('image', models.ImageField(upload_to='Awards')),
                ('alt_text', models.CharField(blank=True, max_length=300)),
                ('year', models.CharField(max_length=4)),
            ],
        ),
    ]
