# Generated by Django 5.1.5 on 2026-01-26 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0038_awards'),
    ]

    operations = [
        migrations.CreateModel(
            name='Awardss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=1256)),
                ('image', models.ImageField(upload_to='Awards')),
                ('image_alt', models.CharField(blank=True, max_length=156, null=True)),
                ('year', models.CharField(max_length=156)),
            ],
        ),
    ]
