# Generated by Django 5.2 on 2026-02-06 08:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0039_awardss'),
    ]

    operations = [
        migrations.AddField(
            model_name='dentist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dentist',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
