# Generated by Django 5.2 on 2026-02-18 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0040_dentist_created_at_dentist_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='faq',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
