# Generated by Django 5.2 on 2026-06-09 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0041_blog_faq'),
    ]

    operations = [
        migrations.AddField(
            model_name='dentist',
            name='certificate_code',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
