# Generated by Django 5.2 on 2026-06-10 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0042_dentist_certificate_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='DentistDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h1', models.CharField(max_length=156)),
                ('title', models.CharField(blank=True, max_length=300, null=True)),
                ('name', models.CharField(max_length=1256)),
                ('certificate_code', models.CharField(blank=True, max_length=300, null=True)),
                ('slug', models.CharField(max_length=1256)),
                ('canonical', models.CharField(blank=True, default='https://ultimatesmiledesign.com/', max_length=900, null=True)),
                ('description', models.TextField(blank=True, max_length=15622, null=True)),
                ('contact', models.CharField(max_length=300)),
                ('clinic_name', models.CharField(blank=True, max_length=1256, null=True)),
                ('address', models.TextField(blank=True, max_length=15622, null=True)),
                ('state', models.CharField(blank=True, max_length=300, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('long', models.FloatField(blank=True, null=True)),
                ('iframe', models.TextField(blank=True, max_length=1300, null=True)),
                ('details_page_image', models.ImageField(blank=True, null=True, upload_to='DentistImage/details-page')),
                ('list_page_image', models.ImageField(blank=True, null=True, upload_to='DentistImage/list-page')),
                ('status', models.BooleanField(default=False)),
                ('schema', models.TextField(blank=True, max_length=15622, null=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.city')),
            ],
        ),
    ]
