# Generated by Django 5.2 on 2026-07-15 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0043_dentistdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactHomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=1256, null=True)),
                ('email', models.CharField(blank=True, max_length=1256, null=True)),
                ('phone', models.CharField(max_length=156)),
                ('city', models.CharField(blank=True, max_length=156, null=True)),
                ('message', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='patientreview',
            name='dentist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='account.dentistdetails'),
        ),
    ]
