# Generated by Django 5.2 on 2026-09-02 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0044_contacthomepage_alter_patientreview_dentist'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallRecordingTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=156, null=True)),
                ('city', models.CharField(blank=True, max_length=156, null=True)),
                ('subject', models.CharField(blank=True, max_length=255, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('call_id', models.CharField(blank=True, max_length=255, null=True)),
                ('call_status', models.CharField(blank=True, max_length=100, null=True)),
                ('recording_url', models.URLField(blank=True, max_length=2048, null=True)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='call_recordings/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='patientreview',
            name='dentist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='account.dentist'),
        ),
    ]
