# Generated by Django 5.2 on 2026-09-08 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0045_callrecordingtest_alter_patientreview_dentist'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubmission',
            name='is_cancel',
            field=models.BooleanField(default=False),
        ),
    ]
