# Generated by Django 5.2 on 2026-09-08 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0046_usersubmission_is_cancel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubmission',
            name='is_cancel',
            field=models.BooleanField(default=True),
        ),
    ]
