# Generated by Django 5.2 on 2026-09-10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0048_alter_usersubmission_is_cancel'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubmission',
            name='source',
            field=models.CharField(blank=True, default='website', help_text='Lead source: calling_agent, voice_agent, website, etc.', max_length=50, null=True),
        ),
    ]
