# Generated by Django 5.2 on 2026-09-17 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0049_usersubmission_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='callrecordingtest',
            name='zoho_id',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True),
        ),
    ]
