# Generated by Django 5.2 on 2026-09-24 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0050_callrecordingtest_zoho_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubmission',
            name='pinconde',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
