# Generated by Django 5.2 on 2026-09-24 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0051_usersubmission_pinconde'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersubmission',
            old_name='pinconde',
            new_name='pincode',
        ),
    ]
