# Generated by Django 5.2 on 2026-09-24 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0052_rename_pinconde_usersubmission_pincode'),
    ]

    operations = [
        migrations.AddField(
            model_name='dentist',
            name='pincode',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
