# Generated by Django 5.2 on 2026-09-24 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0053_dentist_pincode'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='pincode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='dentistconnectnew',
            name='pincode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='smiledesignlead',
            name='pincode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
