# Generated by Django 5.2 on 2026-09-24 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0054_contact_pincode_dentistconnectnew_pincode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacthomepage',
            name='pincode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
