# Generated by Django 6.0.1 on 2026-01-08 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('virtualsmileAI', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smiledesignlead',
            name='after_image',
        ),
        migrations.RemoveField(
            model_name='smiledesignlead',
            name='before_image',
        ),
    ]
