# Generated by Django 6.0 on 2026-01-08 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtualsmileAI', '0002_remove_smiledesignlead_after_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smiledesignlead',
            name='city',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='smiledesignlead',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='smiledesignlead',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
