# Generated by Django 6.0 on 2026-01-08 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtualsmileAI', '0003_alter_smiledesignlead_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='smiledesignlead',
            name='after_image',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='smiledesignlead',
            name='before_image',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
