# Generated by Django 6.0.1 on 2026-01-21 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtualsmileAI', '0004_smiledesignlead_after_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smiledesignlead',
            name='message',
        ),
        migrations.AddField(
            model_name='smiledesignlead',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
