# Generated by Django 6.0.5 on 2026-09-26 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("virtualsmileAI", "0005_remove_smiledesignlead_message_smiledesignlead_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="smiledesignlead",
            name="pincode",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
